/*
WITHOUT LIMITING THE FOREGOING, COPYING, REPRODUCTION, REDISTRIBUTION,
REVERSE ENGINEERING, DISASSEMBLY, DECOMPILATION OR MODIFICATION
OF THE SOFTWARE IS EXPRESSLY PROHIBITED, UNLESS SUCH COPYING,
REPRODUCTION, REDISTRIBUTION, REVERSE ENGINEERING, DISASSEMBLY,
DECOMPILATION OR MODIFICATION IS EXPRESSLY PERMITTED BY THE LICENSE
AGREEMENT WITH NETCRACKER.

THIS SOFTWARE IS WARRANTED, IF AT ALL, ONLY AS EXPRESSLY PROVIDED IN
THE TERMS OF THE LICENSE AGREEMENT, EXCEPT AS WARRANTED IN THE
LICENSE AGREEMENT, NETCRACKER HEREBY DISCLAIMS ALL WARRANTIES AND
CONDITIONS WITH REGARD TO THE SOFTWARE, WHETHER EXPRESS, IMPLIED
OR STATUTORY, INCLUDING WITHOUT LIMITATION ALL WARRANTIES AND
CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
TITLE AND NON-INFRINGEMENT.

Copyright (c) 1995-2013 NetCracker Technology Corp.

All Rights Reserved.
*/

/**
 * Class:
 * Description:
 * <p/>
 * Created by: geal0913
 * Date: 02.04.2015
 */
public class SimpleTest {
    public static void main(String[] args) {
//        Map<String, List<String>> map = new HashMap<String, List<String>>();
//        List<String> ll1 = new ArrayList<>();
//        ll1.add("1");
//        ll1.add("2");
//        ll1.add("3");
//
//        map.put("123", ll1);
//
//        System.out.println(map.get("123"));
//        map.get("123").add("4");
//
//        System.out.println(map.get("123"));

    }
}
